default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: storebase_development
  host: <%= Rails.application.credentials.psql_dev[:host] %>
  port: <%= Rails.application.credentials.psql_dev[:port] %>
  username: <%= Rails.application.credentials.psql_dev[:username] %>
  password: <%= Rails.application.credentials.psql_dev[:password] %>

test:
  <<: *default
  database: storebase_test
  host: <%= Rails.application.credentials.psql_test[:host] %>
  port: <%= Rails.application.credentials.psql_test[:port] %>
  username: <%= Rails.application.credentials.psql_test[:username] %>
  password: <%= Rails.application.credentials.psql_test[:password] %>

production:
  <<: *default
  database: storebase_production
  username: <%= Rails.application.credentials.psql_prod[:username] %>
  password: <%= Rails.application.credentials.psql_prod[:password] %>
