# Admin
Admin.create!(email: 'admin@example.com', password: '123123')

# User
5.times do |i|
  User.create!(
    email: "test#{i + 1}@example.com",
    password: '123456',
    user_name: "test#{i + 1}",
    first_name: "test#{i + 1}",
    last_name: "user#{i + 1}",
    company_name: "company#{i + 1}",
    avatar: "avatar#{i + 1}.jpeg"
  )
end

User.second.update(avatar: nil)

# Platform
Platform.create!(name: 'Shopify')
Platform.create!(name: 'Etsy')

# Service
# for Shopify
Platform.first.services.create!(name: 'Products', icon: nil)
Platform.first.services.create!(name: 'Customers', icon: nil)
# for Etsy
Platform.second.services.create!(name: 'Listing', icon: nil)

# ServiceFormat
services = Service.all
# Products
services[0].service_formats.create!(version: '1', active: true, current: false)
services[0].service_formats.create!(version: '2', active: true, current: true)
services[0].service_formats.create!(version: '3', active: false, current: false)
# Customer
services[1].service_formats.create!(version: '1', active: true, current: false)
services[1].service_formats.create!(version: '2', active: true, current: true)
# Listing
services[2].service_formats.create!(version: '1', active: true, current: false)
services[2].service_formats.create!(version: '2', active: true, current: true)

# Product
service_formats = ServiceFormat.all
service_formats[0].service_cols.create!(ec_column: "Handle", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Title", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Body (HTML)", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Product Category", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Type", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Tags", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Published", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Option1 Name", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Option1 Value", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Option2 Name", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Option2 Value", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Option3 Name", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Option3 Value", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Variant SKU", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Variant Grams", data_type: "integer")
service_formats[0].service_cols.create!(ec_column: "Variant Inventory Tracker", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Variant Inventory Qty", data_type: "integer")
service_formats[0].service_cols.create!(ec_column: "Variant Inventory Policy", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Variant Fulfillment Service", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Variant Price", data_type: "integer")
service_formats[0].service_cols.create!(ec_column: "Variant Compare At Price", data_type: "integer")
service_formats[0].service_cols.create!(ec_column: "Variant Requires Shipping", data_type: "bool")
service_formats[0].service_cols.create!(ec_column: "Variant Taxable", data_type: "bool")
service_formats[0].service_cols.create!(ec_column: "Variant Barcode", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Image Src", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Image Position", data_type: "integer")
service_formats[0].service_cols.create!(ec_column: "Image Alt Text", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Gift Card", data_type: "bool")
service_formats[0].service_cols.create!(ec_column: "SEO Title", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "SEO Description", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / Google Product Category", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / Gender", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / Age Group", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / MPN", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / Condition", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / Custom Product", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / Custom Label 0", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / Custom Label 1", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / Custom Label 2", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / Custom Label 3", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Google Shopping / Custom Label 4", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Variant Image", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Variant Weight Unit", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Variant Tax Code", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Cost per item", data_type: "integer")
service_formats[0].service_cols.create!(ec_column: "Included / Canada", data_type: "bool")
service_formats[0].service_cols.create!(ec_column: "Included / International", data_type: "bool")
service_formats[0].service_cols.create!(ec_column: "Price / International", data_type: "integer")
service_formats[0].service_cols.create!(ec_column: "Compare At Price / International", data_type: "integer")
service_formats[0].service_cols.create!(ec_column: "Included / United States", data_type: "bool")
service_formats[0].service_cols.create!(ec_column: "Price / United States", data_type: "integer")
service_formats[0].service_cols.create!(ec_column: "Compare At Price / United States", data_type: "integer")
service_formats[0].service_cols.create!(ec_column: "Status", data_type: "string")
service_formats[0].service_cols.create!(ec_column: "Vendor", data_type: "string")

service_formats[1].service_cols.create!(ec_column: "Handle", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Title", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Title2", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Body (HTML)", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Product Category", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Type", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Tags", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Published", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Option1 Name", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Option1 Value", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Option2 Name", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Option2 Value", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Option3 Name", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Option3 Value", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Variant SKU", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Variant Grams", data_type: "integer")
service_formats[1].service_cols.create!(ec_column: "Variant Inventory Tracker", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Variant Inventory Qty", data_type: "integer")
service_formats[1].service_cols.create!(ec_column: "Variant Inventory Policy", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Variant Fulfillment Service", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Variant Price", data_type: "integer")
service_formats[1].service_cols.create!(ec_column: "Variant Compare At Price", data_type: "integer")
service_formats[1].service_cols.create!(ec_column: "Variant Requires Shipping", data_type: "bool")
service_formats[1].service_cols.create!(ec_column: "Variant Taxable", data_type: "bool")
service_formats[1].service_cols.create!(ec_column: "Variant Barcode", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Image Src", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Image Position", data_type: "integer")
service_formats[1].service_cols.create!(ec_column: "Image Alt Text", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Gift Card", data_type: "bool")
service_formats[1].service_cols.create!(ec_column: "SEO Title", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "SEO Description", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / Google Product Category", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / Gender", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / Age Group", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / MPN", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / Condition", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / Custom Product", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / Custom Label 0", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / Custom Label 1", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / Custom Label 2", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / Custom Label 3", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Google Shopping / Custom Label 4", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Variant Image", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Variant Weight Unit", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Variant Tax Code", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Cost per item", data_type: "integer")
service_formats[1].service_cols.create!(ec_column: "Included / Canada", data_type: "bool")
service_formats[1].service_cols.create!(ec_column: "Included / International", data_type: "bool")
service_formats[1].service_cols.create!(ec_column: "Price / International", data_type: "integer")
service_formats[1].service_cols.create!(ec_column: "Compare At Price / International", data_type: "integer")
service_formats[1].service_cols.create!(ec_column: "Included / United States", data_type: "bool")
service_formats[1].service_cols.create!(ec_column: "Price / United States", data_type: "integer")
service_formats[1].service_cols.create!(ec_column: "Compare At Price / United States", data_type: "integer")
service_formats[1].service_cols.create!(ec_column: "Status", data_type: "string")
service_formats[1].service_cols.create!(ec_column: "Vendor", data_type: "string")

service_formats[2].service_cols.create!(ec_column: "Handle", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Title", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Title (secondary)", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Body (HTM)", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Product Category", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Type", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Tags", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Published", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Option1 Name", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Option1 Value", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Option2 Name", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Option2 Value", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Option3 Name", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Option3 Value", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Variant SKU", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Variant Grams", data_type: "integer")
service_formats[2].service_cols.create!(ec_column: "Variant Inventory Tracker", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Variant Inventory Qty", data_type: "integer")
service_formats[2].service_cols.create!(ec_column: "Variant Inventory Policy", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Variant Fulfillment Service", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Variant Price", data_type: "integer")
service_formats[2].service_cols.create!(ec_column: "Variant Compare At Price", data_type: "integer")
service_formats[2].service_cols.create!(ec_column: "Variant Requires Shipping", data_type: "bool")
service_formats[2].service_cols.create!(ec_column: "Variant Taxable", data_type: "bool")
service_formats[2].service_cols.create!(ec_column: "Variant Barcode", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Image Src", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Image Position", data_type: "integer")
service_formats[2].service_cols.create!(ec_column: "Image Alt Text", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Gift Card", data_type: "bool")
service_formats[2].service_cols.create!(ec_column: "SEO Title", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "SEO Description", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / Google Product Category", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / Gender", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / Age Group", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / MPN", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / Condition", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / Custom Product", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / Custom Label 0", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / Custom Label 1", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / Custom Label 2", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / Custom Label 3", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Google Shopping / Custom Label 4", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Variant Image", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Variant Weight Unit", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Variant Tax Code", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Cost per item", data_type: "integer")
service_formats[2].service_cols.create!(ec_column: "Included / Canada", data_type: "bool")
service_formats[2].service_cols.create!(ec_column: "Included / International", data_type: "bool")
service_formats[2].service_cols.create!(ec_column: "Price / International", data_type: "integer")
service_formats[2].service_cols.create!(ec_column: "Compare At Price / International", data_type: "integer")
service_formats[2].service_cols.create!(ec_column: "Included / United States", data_type: "bool")
service_formats[2].service_cols.create!(ec_column: "Price / United States", data_type: "integer")
service_formats[2].service_cols.create!(ec_column: "Compare At Price / United States", data_type: "integer")
service_formats[2].service_cols.create!(ec_column: "Status", data_type: "string")
service_formats[2].service_cols.create!(ec_column: "Vendor", data_type: "string")

# Customer
service_formats[3].service_cols.create!(ec_column: "First Name", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Last Name", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Email", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Accepts Email Marketing", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Company", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Address1", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Address2", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "City", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Province", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Province Code", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Country", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Country Code", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Zip", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Phone", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Accepts SMS Marketing", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Total Spent", data_type: "integer")
service_formats[3].service_cols.create!(ec_column: "Total Orders", data_type: "integer")
service_formats[3].service_cols.create!(ec_column: "Tags", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Note", data_type: "string")
service_formats[3].service_cols.create!(ec_column: "Tax Exempt", data_type: "string")

service_formats[4].service_cols.create!(ec_column: "First Name", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Last Name", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Email Address", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Accepts Email Marketing", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Company", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Address1", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Address2", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "City", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Province", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Province Code", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Country", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Country Code", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Zip", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Phone", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Accepts SMS Marketing", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Total Spent", data_type: "integer")
service_formats[4].service_cols.create!(ec_column: "Total Orders", data_type: "integer")
service_formats[4].service_cols.create!(ec_column: "Tags", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Note", data_type: "string")
service_formats[4].service_cols.create!(ec_column: "Tax Exempt", data_type: "string")

# Listing
service_formats[5].service_cols.create!(ec_column: 'quantity', data_type: 'integer')
service_formats[5].service_cols.create!(ec_column: 'title', data_type: 'string')
service_formats[5].service_cols.create!(ec_column: 'description', data_type: 'string')
service_formats[5].service_cols.create!(ec_column: 'price', data_type: 'integer')
service_formats[5].service_cols.create!(ec_column: 'materials', data_type: 'string')
service_formats[5].service_cols.create!(ec_column: 'shipping_template_id', data_type: 'integer')
service_formats[5].service_cols.create!(ec_column: 'taxonomy_id', data_type: 'integer')
service_formats[5].service_cols.create!(ec_column: 'shop_section_id', data_type: 'integer')
service_formats[5].service_cols.create!(ec_column: 'image_ids', data_type: 'integer')
service_formats[5].service_cols.create!(ec_column: 'is_customizable', data_type: 'bool')
service_formats[5].service_cols.create!(ec_column: 'non_taxable', data_type: 'bool')
service_formats[5].service_cols.create!(ec_column: 'image', data_type: 'string')
service_formats[5].service_cols.create!(ec_column: 'state', data_type: 'string')
service_formats[5].service_cols.create!(ec_column: 'processing_min', data_type: 'integer')
service_formats[5].service_cols.create!(ec_column: 'processing_max', data_type: 'integer')
service_formats[5].service_cols.create!(ec_column: 'tags', data_type: 'string')
service_formats[5].service_cols.create!(ec_column: 'who_made', data_type: 'string')
service_formats[5].service_cols.create!(ec_column: 'is_supply', data_type: 'bool')
service_formats[5].service_cols.create!(ec_column: 'when_made', data_type: 'string')
service_formats[5].service_cols.create!(ec_column: 'style', data_type: 'string')

service_formats[6].service_cols.create!(ec_column: 'quantity', data_type: 'integer')
service_formats[6].service_cols.create!(ec_column: 'name', data_type: 'string')
service_formats[6].service_cols.create!(ec_column: 'description', data_type: 'string')
service_formats[6].service_cols.create!(ec_column: 'price', data_type: 'integer')
service_formats[6].service_cols.create!(ec_column: 'materials', data_type: 'string')
service_formats[6].service_cols.create!(ec_column: 'shipping_template_id', data_type: 'integer')
service_formats[6].service_cols.create!(ec_column: 'taxonomy_id', data_type: 'integer')
service_formats[6].service_cols.create!(ec_column: 'shop_section_id', data_type: 'integer')
service_formats[6].service_cols.create!(ec_column: 'image_ids', data_type: 'integer')
service_formats[6].service_cols.create!(ec_column: 'is_customizable', data_type: 'bool')
service_formats[6].service_cols.create!(ec_column: 'non_taxable', data_type: 'bool')
service_formats[6].service_cols.create!(ec_column: 'image', data_type: 'string')
service_formats[6].service_cols.create!(ec_column: 'state', data_type: 'string')
service_formats[6].service_cols.create!(ec_column: 'processing_min', data_type: 'integer')
service_formats[6].service_cols.create!(ec_column: 'processing_max', data_type: 'integer')
service_formats[6].service_cols.create!(ec_column: 'tags', data_type: 'string')
service_formats[6].service_cols.create!(ec_column: 'who_made', data_type: 'string')
service_formats[6].service_cols.create!(ec_column: 'is_supply', data_type: 'bool')
service_formats[6].service_cols.create!(ec_column: 'when_made', data_type: 'string')
service_formats[6].service_cols.create!(ec_column: 'style', data_type: 'string')

# Feature
User.first.features.create!(service_id: services[0].id)
User.first.features.create!(service_id: services[1].id)
User.first.features.create!(service_id: services[2].id)

User.second.features.create!(service_id: services[0].id)
User.second.features.create!(service_id: services[2].id)
